@startuml
'https://plantuml.com/class-diagram

'!pragma layout smetana
'left to right direction

class DeliveryOrder{
    + id: uuid
    + destination: Location
    - status: DeliveryOrderStatus

    create(id: DeliveryOrderId, destination: Location)
    deriveStatusFromCourier(courier: Courier)
    status(): DeliveryOrderStatus
}

class Courier {
    + id: uuid
    + name: String
    - location: Location

    create(name: String, transportType: TransportType, location: Location)
    location(): Location

    assignOrder(order: DeliveryOrder)
    getAssignments(): List<DeliveryOrderAssignment>

    startNextDelivery()
    getCurrentDeliveryOrderId()
    completeCurrentDelivery()
    cancelDeliveryOrder(orderId: DeliveryOrderId)
    status(): CourierStatus

    estimateTimeToReachLocation(targetLocation: Location): Int
    stepToCurrentDeliveryDestination()
}

class TransportType{
    id
    name
    speed
}
class Address  {
    city
    street
    building
    flat
}
hide Address

struct Location{
    x
    y
}

class Customer {
    firstName
    lastName
}
hide Customer

class DeliveryOrderAssignment{
    + id: uuid
    + orderDestination: Location
    - status: AssignmentStatus
    create(order: DeliveryOrder, courier: Courier)
    setStatus(newStatus: AssignmentStatus)
    status(): AssignmentStatus
}

Courier -r-> TransportType
DeliveryOrderAssignment -u-o Courier
DeliveryOrderAssignment -r-> DeliveryOrder
DeliveryOrder -r-> Customer : receiver

enum DeliveryOrderStatus {
ЖдетНазначения
Назначена
Доставлена
Возвращена отправителю
}

enum CourierStatus {
Свободен
Занят
}

enum AssignmentStatus {
    Создано
    Выполняется
    Выполнено
    Отменено
}


 DeliveryOrderAssignment -d[hidden]-> AssignmentStatus
 AssignmentStatus -r[hidden]-> DeliveryOrderStatus
 DeliveryOrderStatus -[hidden]> CourierStatus
 AssignmentStatus -l[hidden]> Location

@enduml