@startuml
'https://plantuml.com/class-diagram

'!pragma layout smetana
'left to right direction

class Посылка{
    /статус: СтатусПосылки
}

class Курьер {
    /статус: СтатусКурьера
}

class Адрес
class Координаты{
    широта
    долгота
}
class Клиент

class ЗаданиеНаДоставку{
    статус: СтатусЗадания
}

Адрес -l-> Координаты
Курьер --> Координаты
ЗаданиеНаДоставку --> Курьер
ЗаданиеНаДоставку -r-> Посылка
Клиент -l-> Адрес

enum СтатусПосылки {
ЖдетНазначения
Назначена
Доставлена
}

enum СтатусКурьера {
Занят
Свободен
}

enum СтатусЗадания {
    Создано
    Выполняется
    Выполнено
    Отменено
}

Координаты -d[hidden]--> СтатусПосылки
СтатусПосылки -[hidden]> СтатусКурьера
СтатусКурьера -[hidden]> СтатусЗадания

@enduml