@startuml
'https://plantuml.com/class-diagram

'!pragma layout smetana
'left to right direction

class Посылка{
    /статус: СтатусПосылки
}

class Курьер {
    ФИО
    /статус: СтатусКурьера
}

class ВидТранспорта{
    скорость
}
class Адрес {
    город
    улица
    дом
    квартира
}
struct Координаты{
    широта
    долгота
}
class Клиент {
    ФИО
}

class ЗаданиеНаДоставку{
    статус: СтатусЗадания
}

Адрес -l-> Координаты
Курьер -r-> Координаты
Курьер -d-> ВидТранспорта
ЗаданиеНаДоставку --> Курьер
ЗаданиеНаДоставку -r-> Посылка : "                         "
Посылка -r-> Клиент : получатель
Посылка --> Адрес : адрес доставки

enum СтатусПосылки {
ЖдетНазначения
Назначена
Доставлена
}

enum СтатусКурьера {
Занят
Свободен
}

enum СтатусЗадания {
    Создано
    Выполняется
    Выполнено
    Отменено
}

ВидТранспорта -d[hidden]--> СтатусПосылки
СтатусПосылки -[hidden]> СтатусКурьера
СтатусКурьера -[hidden]> СтатусЗадания

@enduml