@startuml
'https://plantuml.com/class-diagram

'!pragma layout smetana
'left to right direction

class DeliveryOrder{
    id: uuid
    destination: Location
    /status: DeliveryOrderStatus
}

class Courier {
    id: uuid
    name: String
    location: Location
    /status: CourierStatus
}

class TransportType{
    id
    name
    speed
}
class Address  {
    city
    street
    building
    flat
}
hide Address

struct Location{
    x
    y
}
class Customer {
    firstName
    lastName
}

class DeliveryOrderAssignment{
    status: AssignmentStatus
}

'DeliveryOrder -d-> Location
'Courier -r-> Location

Courier -d-> TransportType
DeliveryOrderAssignment --* Courier
DeliveryOrderAssignment -r-> DeliveryOrder
DeliveryOrder -r-> Customer : receiver

enum DeliveryOrderStatus {
ЖдетНазначения
Назначена
Доставлена
}

enum CourierStatus {
Свободен
Занят
}

enum AssignmentStatus {
    Создано
    Выполняется
    Выполнено
    Отменено
}

TransportType -d[hidden]--> DeliveryOrderStatus
DeliveryOrderStatus -[hidden]> CourierStatus
CourierStatus -[hidden]> AssignmentStatus
AssignmentStatus -[hidden]> Location

@enduml